### ISSUE TITLE
Bug in Dark Mode

### ISSUE THREAD

**Issue by PravinPadalkar78** [chintan0513/ToDo-List#16]
The Tasks are Not Visible in Dark mode 
![image](https://user-images.githubusercontent.com/94164210/195167370-3fd90223-6b17-4cd7-93e4-db53ac8a9796.png)

Please assign this issue to me with lable #hacktoberfest
thanks

**Comment by VIJAYKATARI23** [comment]
Please assign this issue to me with Hacktoberfest tag.

**Comment by YashGadia** [comment]
@chintan0513 I can fix this. Please assign this issue to me with hacktoberfest tag.

**Comment by chintan0513** [comment]
Already in process. Thank you. 

Closing here #16

**Comment by rehanrawat** [comment]
Todo list items are still not visible in dark mode.
