### ISSUE TITLE
required info

### ISSUE THREAD

**Issue by hritikbhattacharya** [chintan0513/ToDo-List#17]
Is this repo is accepted in hacktoberfest 2022 .and can I contribute to it?

**Comment by chintan0513** [comment]
Yes you can, just refer current issue and you are good to go ✔️

**Comment by hritikbhattacharya** [comment]
> Yes you can, just refer current issue and you are good to go ✔️

ok thank you for the information

**Comment by VIJAYKATARI23** [comment]
Please assign this issue to me with Hacktoberfest tag.

**Comment by chintan0513** [comment]
if @hritikbhattacharya okay with it then you can work on it.
