### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by chintan0513** [chintan0513/ToDo-List#9]
I would appreciate it if you modify the style of the task list.

**Comment by OkenHaha** [comment]
Let me work on this

**Comment by jatin00000** [comment]
Please Sir can you assign this issue to me.

**Comment by kartiksaxena532** [comment]
hi sir please let me work on it

**Comment by chintan0513** [comment]
Okay ✔️

**Comment by VIJAYKATARI23** [comment]
Please assign this issue to me with Hacktoberfest tag.
